@Agregator.API_HostAddress = http://localhost:5167

GET {{Agregator.API_HostAddress}}/api/orders/
Accept: application/json

###
Post {{Agregator.API_HostAddress}}/api/orders/
Accept: application/json
Content-type: application/json

[
  {
    "productId": "a-456",
    "quantity": 5
  },
  {
    "productId": "d-789",
    "quantity": 42
  }
]
